### ISSUE TITLE
Question about Database Transactions

### ISSUE THREAD

**Issue by jadencarver** [nodeontrain/trainjs#14]
I'm reading through the code here trying to see if this tool generates code that gracefully manages database transactions, errors and appropriate `ROLLBACK` features.  I'm not seeing anything that would indicate that it does.

Can the maintainers here confirm this?  For my purposes, I need to ensure that an error in my code does not create inconsistencies in my database.

**Comment by train255** [comment]
I've used sequelizejs. You may refer [here](http://docs.sequelizejs.com/en/latest/docs/transactions)

**Comment by jadencarver** [comment]
Oh yes. I know - they are very difficult to do, which is why I was hoping trainjs might have them baked in, like how Rails does.  I don't see anything in the (controllers)[https://github.com/nodeontrain/trainjs/blob/master/template/scaffold/app/controllers/controller.js] or elsewhere, so I think it's safe to say the answer is no.

I will close this comment, but consider it a feature request.  I definitely like the structure you have laid out here.  Great job!

**Comment by train255** [comment]
Thank you very much, I'll do my best. Maybe you also help me :)
