### ISSUE TITLE
Why am I getting emails from Node on Train?

### ISSUE THREAD

**Issue by alexbooker** [nodeontrain/trainjs#15]
I got this email from admin@nodeontrain.xyz:

![](http://i.imgur.com/LxrRG4v.png)

**Why?**

I never subscribed.

**Comment by train255** [comment]
I'm sorry about the misunderstanding (this is because I use a template for subscriber to send email). This is an email for [all those who care about the sequelizejs](https://github.com/sequelize/sequelize/stargazers). I'm sorry to trouble you.

**Comment by alexbooker** [comment]
Ok :disappointed: 

It's cool.
