### ISSUE TITLE
`trainjs generate controller StaticPages home help` does not create `public/test` directory

### ISSUE THREAD

**Issue by piotrlewandowski** [nodeontrain/trainjs#20]
I'm trying to follow the tutorial and when running `trainjs generate controller StaticPages home help` command, it doesn't create the `public/test` directory as stated in the tutorial.
Tried on:
- node 5.12.0 & npm 3.8.6
- node 6.9.1 & npm 3.10.8

**Comment by train255** [comment]
Thanks for your report. I fixed it in the latest version
